### ISSUE TITLE
-o Parameter not used

### ISSUE THREAD

**Issue by AuxiliumCDNG** [malcx95/gopro-merger#1]
Hey!
Thanks for sharing this very helpful script! Works pretty well for me!

However, I noticed that the newly created clips are saved to the input directory instead of the output you specify in the cli.
I changed this part of your code: https://github.com/malcx95/gopro-merger/blob/master/gopro.py#L40C89-L40C99

To:
`"ffmpeg", "-f", "concat", "-safe", "0", "-i", list_file_name, "-c", "copy", output_path / (name + ".mp4")`

With this change, the processed files will be saved to the directory you specify.

Thanks for your time :)

**Comment by malcx95** [comment]
Hi!

Thanks for the heads up and I'm glad you found the script useful! This was something I just threw together quickly as I got tired of the files being split all the time. Fixed the issue now.
